platform :ios, '7.0'
pod 'RNThemeManager', :podspec => 'https://raw.githubusercontent.com/joeshang/RNThemeManager/master/RNThemeManager.podspec'
pod 'CHTCollectionViewWaterfallLayout'
pod 'NSObject-ObjectMap'
pod 'BCGenieEffect'
pod 'AFNetworking'
pod 'SVProgressHUD'
pod 'CocoaAsyncSocket'
